name: Dump GitHub Event

on:
  push:

jobs:
  dump:
    runs-on: ubuntu-latest
    steps:
      - name: Dump payload
        run: |
          echo $GITHUB_EVENT
          echo "HELLO"
        env:
          GITHUB_EVENT: ${{ toJson(github) }}
